server:
  port: 25000

spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 59.110.44.147
    port: 6379

logging:
  level:
    com.atguigu.gulimall: debug

