spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: XXX
      secret-key: XXX
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-cy

  application:
    name: gulimall-third-party

server:
  port: 30000
